#include "grammar.h"
#include "lr1.h"
#include "parser.h"
#include "server.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cstring>

Grammar                  buildGrammar();
std::vector<std::string> tokenize(const std::string& line);
void                     printUsage(const char* prog);
void                     writeDataJS(const std::string& json, const std::string& path);

// Write JSON wrapped as a JS const — the visualizer loads this directly
void writeDataJS(const std::string& json, const std::string& path) {
    std::ofstream out(path);
    if (!out) { std::cerr << "Error: cannot write " << path << "\n"; return; }
    out << "// AUTO-GENERATED by lr1_parser.exe — do not edit manually.\n";
    out << "// Regenerate: .\\build\\lr1_parser.exe --write-js \"your tokens\"\n\n";
    out << "const DATA = " << json << ";\n";
    std::cout << "Data   : " << path << "\n";
}

Grammar buildGrammar() {
    Grammar g;
    g.augmentedStart = nonTerminal("S'");
    g.startSymbol    = nonTerminal("S");
    g.terminals.insert(terminal("="));
    g.terminals.insert(terminal("*"));
    g.terminals.insert(terminal("id"));
    g.terminals.insert(END_OF_INPUT);
    g.nonTerminals.insert(nonTerminal("S'"));
    g.nonTerminals.insert(nonTerminal("S"));
    g.nonTerminals.insert(nonTerminal("L"));
    g.nonTerminals.insert(nonTerminal("R"));
    g.productions.push_back({nonTerminal("S'"), {nonTerminal("S")},                                 0});
    g.productions.push_back({nonTerminal("S"),  {nonTerminal("L"), terminal("="), nonTerminal("R")}, 1});
    g.productions.push_back({nonTerminal("S"),  {nonTerminal("R")},                                 2});
    g.productions.push_back({nonTerminal("L"),  {terminal("*"),    nonTerminal("R")},                3});
    g.productions.push_back({nonTerminal("L"),  {terminal("id")},                                   4});
    g.productions.push_back({nonTerminal("R"),  {nonTerminal("L")},                                 5});
    g.computeFirstSets();
    return g;
}

std::vector<std::string> tokenize(const std::string& line) {
    std::vector<std::string> tokens;
    std::istringstream ss(line);
    std::string tok;
    while (ss >> tok) tokens.push_back(tok);
    return tokens;
}

void printUsage(const char* prog) {
    std::cout
        << "\nUsage: " << prog << " [OPTIONS] \"<tokens>\"\n"
        << "\nOptions:\n"
        << "  -o, --output <file>   Write JSON to file (default: lr1_data.json)\n"
        << "  -w, --write-js        Write visualization/js/data.js (JS format)\n"
        << "  -r, --report          Print full text report\n"
        << "  -t, --trace           Print parse trace\n"
        << "  -q, --quiet           Suppress summary\n"
        << "  -j, --json            Print JSON to stdout\n"
        << "  -s, --serve [port]    Start HTTP server (default: 7373)\n"
        << "  -h, --help            Show this help\n"
        << "\nExamples:\n"
        << "  " << prog << " \"id = * id\"\n"
        << "  " << prog << " --write-js \"id = * id\"\n"
        << "  " << prog << " --serve\n\n";
}

int main(int argc, char* argv[]) {
    std::string inputStr  = "id = * id";
    std::string outFile   = "lr1_data.json";
    std::string jsFile    = "visualization/js/data.js";
    bool        doReport  = false;
    bool        doTrace   = false;
    bool        quiet     = false;
    bool        jsonStdout= false;
    bool        writeJS   = false;
    bool        doServe   = false;
    int         port      = 7373;

    for (int i = 1; i < argc; i++) {
        if      (!std::strcmp(argv[i],"-h")||!std::strcmp(argv[i],"--help"))   { printUsage(argv[0]); return 0; }
        else if (!std::strcmp(argv[i],"-r")||!std::strcmp(argv[i],"--report")) { doReport  = true; }
        else if (!std::strcmp(argv[i],"-t")||!std::strcmp(argv[i],"--trace"))  { doTrace   = true; }
        else if (!std::strcmp(argv[i],"-q")||!std::strcmp(argv[i],"--quiet"))  { quiet     = true; }
        else if (!std::strcmp(argv[i],"-j")||!std::strcmp(argv[i],"--json"))   { jsonStdout= true; }
        else if (!std::strcmp(argv[i],"-w")||!std::strcmp(argv[i],"--write-js")){ writeJS  = true; }
        else if (!std::strcmp(argv[i],"-s")||!std::strcmp(argv[i],"--serve"))  {
            doServe = true;
            if (i+1 < argc && std::isdigit(static_cast<unsigned char>(argv[i+1][0])))
                port = std::atoi(argv[++i]);
        }
        else if ((!std::strcmp(argv[i],"-o")||!std::strcmp(argv[i],"--output")) && i+1<argc) {
            outFile = argv[++i];
        }
        else { inputStr = argv[i]; }
    }

    // Build grammar and LR(1) table (always needed)
    Grammar    g = buildGrammar();
    LR1Builder builder(g);
    builder.build();

    // Server mode: blocks until Ctrl+C
    if (doServe) {
        startServer(g, builder.getTable(), builder.getStates(), builder.transitions_, port);
        return 0;
    }

    // Parse the input string
    auto        tokens = tokenize(inputStr);
    Parser      parser(g, builder.getTable());
    ParseResult result = parser.parse(tokens);

    if (!quiet) {
        std::cout << "Input  : " << inputStr                                          << "\n";
        std::cout << "States : " << builder.getStates().size()                        << "\n";
        std::cout << "Conflicts: " << (builder.getTable().hasConflict?"YES":"NONE")   << "\n";
        std::cout << "Result : " << (result.accepted ? "ACCEPTED" : "REJECTED")       << "\n";
        std::cout << "Steps  : " << result.steps.size()                               << "\n";
        if (!result.errorMessage.empty())
            std::cerr << "Error  : " << result.errorMessage << "\n";
    }

    if (doReport)     printFullReport(g, builder, result, std::cout);
    else if (doTrace) printParseTrace(result, std::cout);

    // Generate JSON
    std::string json = serializeToJSON(
        g, builder.getStates(), builder.transitions_, builder.getTable(), result);

    // Write visualization/js/data.js  (primary output path)
    if (writeJS) {
        writeDataJS(json, jsFile);
    }

    // Also write JSON file (always, unless --json to stdout)
    if (jsonStdout) {
        std::cout << json;
    } else if (!writeJS) {
        std::ofstream out(outFile);
        if (!out) { std::cerr << "Error: cannot open " << outFile << "\n"; return 1; }
        out << json;
        if (!quiet) std::cout << "JSON   : " << outFile << "\n";
    }

    return result.accepted ? 0 : 1;
}